-- Goal scorers and optional assists per match
-- Run once in Supabase SQL Editor after match-scores-and-captain-clubs.sql

CREATE TABLE IF NOT EXISTS public.match_goals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id bigint NOT NULL REFERENCES public.matches(id) ON DELETE CASCADE,
  team_id bigint NOT NULL REFERENCES public.teams(id),
  scorer_id bigint NOT NULL REFERENCES public.users(id),
  assist_id bigint REFERENCES public.users(id),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_match_goals_match_id ON public.match_goals(match_id);

ALTER TABLE public.match_goals ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "match_goals_select_authenticated" ON public.match_goals;
DROP POLICY IF EXISTS "match_goals_insert_organizer" ON public.match_goals;
DROP POLICY IF EXISTS "match_goals_update_organizer" ON public.match_goals;
DROP POLICY IF EXISTS "match_goals_delete_organizer" ON public.match_goals;

CREATE POLICY "match_goals_select_authenticated"
  ON public.match_goals
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "match_goals_insert_organizer"
  ON public.match_goals
  FOR INSERT
  TO authenticated
  WITH CHECK (public.is_organizer());

CREATE POLICY "match_goals_update_organizer"
  ON public.match_goals
  FOR UPDATE
  TO authenticated
  USING (public.is_organizer())
  WITH CHECK (public.is_organizer());

CREATE POLICY "match_goals_delete_organizer"
  ON public.match_goals
  FOR DELETE
  TO authenticated
  USING (public.is_organizer());

GRANT SELECT, INSERT, UPDATE, DELETE ON public.match_goals TO authenticated;
