-- ============================================================
-- Touchline — FULL SETUP for a NEW Supabase project
-- ============================================================
-- 1. Paste this ENTIRE file in Supabase → SQL Editor → Run
-- 2. (Optional) Paste supabase/seed.sql for demo clubs & matches
-- 3. Update .env with Project URL + anon key, restart npm run dev
-- 4. Auth → Providers → Email: turn OFF "Confirm email" for easier testing
-- ============================================================

-- ---------------------------------------------------------------------------
-- Schema
-- ---------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

DO $$ BEGIN
  CREATE TYPE public.user_role AS ENUM ('Player', 'Captain', 'Organizer');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE public.match_status AS ENUM ('Scheduled', 'Postponed', 'Completed');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE public.rsvp_status AS ENUM ('Going', 'Out', 'No Response');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.teams (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  primary_kit_color text NOT NULL,
  away_kit_color text NOT NULL,
  invite_code text UNIQUE,
  created_by bigint
);

CREATE TABLE IF NOT EXISTS public.users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_id uuid UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL,
  email text NOT NULL UNIQUE,
  role public.user_role NOT NULL DEFAULT 'Player',
  team_id bigint REFERENCES public.teams(id)
);

DO $$ BEGIN
  ALTER TABLE public.teams
    ADD CONSTRAINT teams_created_by_fkey
    FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS idx_teams_invite_code ON public.teams(invite_code);
CREATE INDEX IF NOT EXISTS idx_users_auth_id ON public.users(auth_id);

CREATE TABLE IF NOT EXISTS public.matches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  home_team_id bigint NOT NULL REFERENCES public.teams(id),
  away_team_id bigint NOT NULL REFERENCES public.teams(id),
  match_date timestamptz NOT NULL,
  field_number integer NOT NULL DEFAULT 1,
  field_address text,
  status public.match_status NOT NULL DEFAULT 'Scheduled',
  assigned_home_kit text NOT NULL,
  assigned_away_kit text NOT NULL,
  home_score integer,
  away_score integer
);

CREATE TABLE IF NOT EXISTS public.rsvps (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id bigint NOT NULL REFERENCES public.matches(id) ON DELETE CASCADE,
  user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  status public.rsvp_status NOT NULL DEFAULT 'No Response',
  UNIQUE (match_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text text NOT NULL,
  sender_name text NOT NULL,
  "timestamp" timestamptz NOT NULL DEFAULT now(),
  team_id bigint REFERENCES public.teams(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_messages_team_id ON public.messages(team_id);

CREATE TABLE IF NOT EXISTS public.match_goals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id bigint NOT NULL REFERENCES public.matches(id) ON DELETE CASCADE,
  team_id bigint NOT NULL REFERENCES public.teams(id),
  scorer_id bigint NOT NULL REFERENCES public.users(id),
  assist_id bigint REFERENCES public.users(id),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_match_goals_match_id ON public.match_goals(match_id);

INSERT INTO public.teams (id, name, primary_kit_color, away_kit_color)
VALUES (1, 'Emerald City FC', 'Emerald Green', 'White')
ON CONFLICT (id) DO NOTHING;

-- Sync teams id sequence (no result row in SQL editor)
DO $$
BEGIN
  PERFORM setval(
    pg_get_serial_sequence('public.teams', 'id'),
    GREATEST((SELECT COALESCE(MAX(id), 1) FROM public.teams), 1)
  );
END $$;

-- ---------------------------------------------------------------------------
-- Auth signup → profile trigger
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  meta jsonb := COALESCE(NEW.raw_user_meta_data, '{}'::jsonb);
  chosen_role public.user_role := 'Player';
  chosen_team bigint := NULLIF(meta->>'team_id', '')::bigint;
  resolved_team bigint;
  profile_name text;
BEGIN
  INSERT INTO public.teams (id, name, primary_kit_color, away_kit_color)
  VALUES (1, 'Emerald City FC', 'Emerald Green', 'White')
  ON CONFLICT (id) DO NOTHING;

  BEGIN
    chosen_role := COALESCE((meta->>'role')::public.user_role, 'Player');
  EXCEPTION
    WHEN invalid_text_representation THEN
      chosen_role := 'Player';
  END;

  profile_name := COALESCE(
    NULLIF(TRIM(COALESCE(meta->>'name', '')), ''),
    split_part(NEW.email, '@', 1)
  );

  resolved_team := CASE
    WHEN chosen_role = 'Organizer' THEN NULL
    WHEN chosen_team IS NOT NULL THEN chosen_team
    WHEN chosen_role = 'Player' THEN NULL
    ELSE 1
  END;

  UPDATE public.users
  SET
    auth_id = NEW.id,
    name = profile_name,
    role = chosen_role,
    team_id = resolved_team
  WHERE email = NEW.email
    AND auth_id IS NULL;

  IF FOUND THEN
    RETURN NEW;
  END IF;

  INSERT INTO public.users (auth_id, name, email, role, team_id)
  VALUES (NEW.id, profile_name, NEW.email, chosen_role, resolved_team)
  ON CONFLICT (auth_id) DO UPDATE
    SET name = EXCLUDED.name,
        role = EXCLUDED.role,
        team_id = EXCLUDED.team_id;

  RETURN NEW;
EXCEPTION
  WHEN unique_violation THEN
    RAISE EXCEPTION 'An account with this email already exists. Try signing in instead.';
  WHEN foreign_key_violation THEN
    RAISE EXCEPTION 'Default team missing. Re-run this script.';
  WHEN OTHERS THEN
    RAISE EXCEPTION 'Profile setup failed: %', SQLERRM;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_auth_user();

-- ---------------------------------------------------------------------------
-- Helper functions
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.auth_user_id()
RETURNS bigint
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$ SELECT id FROM public.users WHERE auth_id = auth.uid() LIMIT 1; $$;

CREATE OR REPLACE FUNCTION public.auth_user_role()
RETURNS public.user_role
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$ SELECT role FROM public.users WHERE auth_id = auth.uid() LIMIT 1; $$;

CREATE OR REPLACE FUNCTION public.auth_user_team_id()
RETURNS bigint
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$ SELECT team_id FROM public.users WHERE auth_id = auth.uid() LIMIT 1; $$;

CREATE OR REPLACE FUNCTION public.auth_user_name()
RETURNS text
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$ SELECT name FROM public.users WHERE auth_id = auth.uid() LIMIT 1; $$;

CREATE OR REPLACE FUNCTION public.is_organizer()
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$ SELECT EXISTS (SELECT 1 FROM public.users WHERE auth_id = auth.uid() AND role = 'Organizer'); $$;

CREATE OR REPLACE FUNCTION public.is_captain()
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$ SELECT EXISTS (SELECT 1 FROM public.users WHERE auth_id = auth.uid() AND role = 'Captain'); $$;

CREATE OR REPLACE FUNCTION public.is_player()
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$ SELECT EXISTS (SELECT 1 FROM public.users WHERE auth_id = auth.uid() AND role = 'Player'); $$;

REVOKE ALL ON FUNCTION public.auth_user_id() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.auth_user_role() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.auth_user_team_id() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.auth_user_name() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.is_organizer() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.is_captain() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.is_player() FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.auth_user_id() TO authenticated;
GRANT EXECUTE ON FUNCTION public.auth_user_role() TO authenticated;
GRANT EXECUTE ON FUNCTION public.auth_user_team_id() TO authenticated;
GRANT EXECUTE ON FUNCTION public.auth_user_name() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_organizer() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_captain() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_player() TO authenticated;

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------
ALTER TABLE public.teams       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.matches     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rsvps       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.match_goals ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "teams_select_public" ON public.teams;
DROP POLICY IF EXISTS "teams_insert_captain" ON public.teams;
DROP POLICY IF EXISTS "users_select_authenticated" ON public.users;
DROP POLICY IF EXISTS "users_insert_own_profile" ON public.users;
DROP POLICY IF EXISTS "users_insert_captain_roster" ON public.users;
DROP POLICY IF EXISTS "users_update_own_profile" ON public.users;
DROP POLICY IF EXISTS "users_update_link_auth" ON public.users;
DROP POLICY IF EXISTS "users_delete_captain_roster" ON public.users;
DROP POLICY IF EXISTS "matches_select_authenticated" ON public.matches;
DROP POLICY IF EXISTS "matches_insert_organizer" ON public.matches;
DROP POLICY IF EXISTS "matches_update_organizer" ON public.matches;
DROP POLICY IF EXISTS "rsvps_select_scoped" ON public.rsvps;
DROP POLICY IF EXISTS "rsvps_insert_own" ON public.rsvps;
DROP POLICY IF EXISTS "rsvps_update_own" ON public.rsvps;
DROP POLICY IF EXISTS "messages_select_scoped" ON public.messages;
DROP POLICY IF EXISTS "messages_insert_as_self" ON public.messages;
DROP POLICY IF EXISTS "messages_insert_league_office" ON public.messages;
DROP POLICY IF EXISTS "match_goals_select_authenticated" ON public.match_goals;
DROP POLICY IF EXISTS "match_goals_insert_organizer" ON public.match_goals;
DROP POLICY IF EXISTS "match_goals_update_organizer" ON public.match_goals;
DROP POLICY IF EXISTS "match_goals_delete_organizer" ON public.match_goals;

REVOKE ALL ON public.teams       FROM anon;
REVOKE ALL ON public.users       FROM anon;
REVOKE ALL ON public.matches     FROM anon;
REVOKE ALL ON public.rsvps       FROM anon;
REVOKE ALL ON public.messages    FROM anon;
REVOKE ALL ON public.match_goals FROM anon;

GRANT SELECT ON public.teams TO authenticated, anon;
GRANT INSERT ON public.teams TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.users TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.matches TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.rsvps TO authenticated;
GRANT SELECT, INSERT ON public.messages TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.match_goals TO authenticated;

CREATE POLICY "teams_select_public"
  ON public.teams FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "teams_insert_captain"
  ON public.teams FOR INSERT TO authenticated
  WITH CHECK (public.is_captain());

CREATE POLICY "users_select_authenticated"
  ON public.users FOR SELECT TO authenticated
  USING (
    auth_id = auth.uid()
    OR public.is_organizer()
    OR (public.auth_user_team_id() IS NOT NULL AND team_id = public.auth_user_team_id())
  );

CREATE POLICY "users_insert_own_profile"
  ON public.users FOR INSERT TO authenticated
  WITH CHECK (auth_id = auth.uid() AND email = (auth.jwt() ->> 'email'));

CREATE POLICY "users_insert_captain_roster"
  ON public.users FOR INSERT TO authenticated
  WITH CHECK (
    public.is_captain()
    AND role = 'Player'
    AND team_id = public.auth_user_team_id()
    AND auth_id IS NULL
  );

CREATE POLICY "users_update_link_auth"
  ON public.users FOR UPDATE TO authenticated
  USING (email = (auth.jwt() ->> 'email') AND auth_id IS NULL)
  WITH CHECK (auth_id = auth.uid() AND email = (auth.jwt() ->> 'email'));

CREATE POLICY "users_update_own_profile"
  ON public.users FOR UPDATE TO authenticated
  USING (auth_id = auth.uid())
  WITH CHECK (auth_id = auth.uid());

CREATE POLICY "users_delete_captain_roster"
  ON public.users FOR DELETE TO authenticated
  USING (
    public.is_captain()
    AND role = 'Player'
    AND team_id = public.auth_user_team_id()
    AND auth_id IS NULL
    AND id <> public.auth_user_id()
  );

CREATE POLICY "matches_select_authenticated"
  ON public.matches FOR SELECT TO authenticated USING (true);

CREATE POLICY "matches_insert_organizer"
  ON public.matches FOR INSERT TO authenticated
  WITH CHECK (public.is_organizer());

CREATE POLICY "matches_update_organizer"
  ON public.matches FOR UPDATE TO authenticated
  USING (public.is_organizer())
  WITH CHECK (public.is_organizer());

CREATE POLICY "rsvps_select_scoped"
  ON public.rsvps FOR SELECT TO authenticated
  USING (
    public.is_organizer()
    OR user_id = public.auth_user_id()
    OR (
      public.auth_user_team_id() IS NOT NULL
      AND EXISTS (
        SELECT 1 FROM public.users u
        WHERE u.id = rsvps.user_id AND u.team_id = public.auth_user_team_id()
      )
    )
  );

CREATE POLICY "rsvps_insert_own"
  ON public.rsvps FOR INSERT TO authenticated
  WITH CHECK (
    public.is_player()
    AND user_id = public.auth_user_id()
    AND status IN ('Going', 'Out', 'No Response')
    AND EXISTS (
      SELECT 1 FROM public.matches m
      WHERE m.id = match_id AND m.status = 'Scheduled'
        AND public.auth_user_team_id() IS NOT NULL
        AND (m.home_team_id = public.auth_user_team_id() OR m.away_team_id = public.auth_user_team_id())
    )
  );

CREATE POLICY "rsvps_update_own"
  ON public.rsvps FOR UPDATE TO authenticated
  USING (public.is_player() AND user_id = public.auth_user_id())
  WITH CHECK (
    public.is_player()
    AND user_id = public.auth_user_id()
    AND status IN ('Going', 'Out', 'No Response')
    AND EXISTS (
      SELECT 1 FROM public.matches m
      WHERE m.id = match_id AND m.status = 'Scheduled'
        AND public.auth_user_team_id() IS NOT NULL
        AND (m.home_team_id = public.auth_user_team_id() OR m.away_team_id = public.auth_user_team_id())
    )
  );

CREATE POLICY "messages_select_scoped"
  ON public.messages FOR SELECT TO authenticated
  USING (
    team_id IS NULL
    OR public.is_organizer()
    OR team_id = public.auth_user_team_id()
  );

CREATE POLICY "messages_insert_as_self"
  ON public.messages FOR INSERT TO authenticated
  WITH CHECK (
    sender_name = public.auth_user_name()
    AND char_length(trim(text)) > 0
    AND (team_id IS NULL OR team_id = public.auth_user_team_id())
  );

CREATE POLICY "messages_insert_league_office"
  ON public.messages FOR INSERT TO authenticated
  WITH CHECK (
    public.is_organizer()
    AND sender_name = 'League Office'
    AND team_id IS NULL
    AND char_length(trim(text)) > 0
  );

CREATE POLICY "match_goals_select_authenticated"
  ON public.match_goals FOR SELECT TO authenticated USING (true);

CREATE POLICY "match_goals_insert_organizer"
  ON public.match_goals FOR INSERT TO authenticated
  WITH CHECK (public.is_organizer());

CREATE POLICY "match_goals_update_organizer"
  ON public.match_goals FOR UPDATE TO authenticated
  USING (public.is_organizer())
  WITH CHECK (public.is_organizer());

CREATE POLICY "match_goals_delete_organizer"
  ON public.match_goals FOR DELETE TO authenticated
  USING (public.is_organizer());

-- ---------------------------------------------------------------------------
-- Profile update rules (join/leave club, captains change club)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.enforce_profile_update_rules()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF OLD.auth_id IS NULL AND NEW.auth_id = auth.uid() THEN
    RETURN NEW;
  END IF;

  IF OLD.auth_id = auth.uid() THEN
    IF NEW.role IS DISTINCT FROM OLD.role
       OR NEW.email IS DISTINCT FROM OLD.email
       OR NEW.auth_id IS DISTINCT FROM OLD.auth_id THEN
      RAISE EXCEPTION 'You cannot change role, email, or auth link.';
    END IF;

    IF NEW.team_id IS DISTINCT FROM OLD.team_id THEN
      IF OLD.role = 'Player' THEN
        IF NEW.team_id IS NOT NULL
           AND NOT EXISTS (SELECT 1 FROM public.teams t WHERE t.id = NEW.team_id) THEN
          RAISE EXCEPTION 'Invalid team selected.';
        END IF;
      ELSIF OLD.role = 'Captain' THEN
        IF NEW.team_id IS NOT NULL
           AND NOT EXISTS (SELECT 1 FROM public.teams t WHERE t.id = NEW.team_id) THEN
          RAISE EXCEPTION 'Invalid team selected.';
        END IF;
      ELSE
        RAISE EXCEPTION 'Only players and captains can change club.';
      END IF;
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS enforce_profile_update_rules ON public.users;
CREATE TRIGGER enforce_profile_update_rules
  BEFORE UPDATE ON public.users
  FOR EACH ROW
  EXECUTE FUNCTION public.enforce_profile_update_rules();
